name: flutter_project
description: "A new Flutter project."
version: 1.0.0+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.5.0

  # HTTP Client
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  timeago: ^3.7.0

  # HTML Rendering
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_remote_config: ^5.4.3
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  shimmer: ^3.0.0
  package_info_plus: ^8.3.0

  # Storage
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.8
  riverpod_generator: ^2.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#1c1c1c"
  image: assets/images/logonobg.png
  android_12:
    color: "#1c1c1c"
    image: assets/images/logonobg.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logonobg.png
    - assets/icons/
    - assets/flags/
