// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIqpcFob3z5RKYaW51vdmNLiP0m29TJuQ',
    appId: '1:889906815635:web:324ff3aea7ffb99eeba366',
    messagingSenderId: '889906815635',
    projectId: 'baca-komik-1-5c2c1',
    authDomain: 'baca-komik-1-5c2c1.firebaseapp.com',
    storageBucket: 'baca-komik-1-5c2c1.firebasestorage.app',
    measurementId: 'G-T99E8HXNDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUpcaCtdQz4dAuD9ZarFvtR-wqx2CsyPk',
    appId: '1:889906815635:android:d2fce72b664d579ceba366',
    messagingSenderId: '889906815635',
    projectId: 'baca-komik-1-5c2c1',
    storageBucket: 'baca-komik-1-5c2c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUyaTvYLaYu548J52iw6JxfdXEOvFgtSo',
    appId: '1:889906815635:ios:2d881ece79507e4deba366',
    messagingSenderId: '889906815635',
    projectId: 'baca-komik-1-5c2c1',
    storageBucket: 'baca-komik-1-5c2c1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUyaTvYLaYu548J52iw6JxfdXEOvFgtSo',
    appId: '1:889906815635:ios:2d881ece79507e4deba366',
    messagingSenderId: '889906815635',
    projectId: 'baca-komik-1-5c2c1',
    storageBucket: 'baca-komik-1-5c2c1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIqpcFob3z5RKYaW51vdmNLiP0m29TJuQ',
    appId: '1:889906815635:web:a62ee07b9036d119eba366',
    messagingSenderId: '889906815635',
    projectId: 'baca-komik-1-5c2c1',
    authDomain: 'baca-komik-1-5c2c1.firebaseapp.com',
    storageBucket: 'baca-komik-1-5c2c1.firebasestorage.app',
    measurementId: 'G-LW6JB3Y2MQ',
  );
}
